<?php
	
	/**
	 * Do not edit this file. Edit the config files found in the config/ dir instead.
	 * This file is required in the root directory so WordPress can find it.
	 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
	 */
	
	// Including the needed classes
	require_once( dirname(__DIR__) . '/vendor/dotenv/Dotenv.php' );
	require_once( dirname(__DIR__) . '/vendor/dotenv/Loader.php' );
	require_once( dirname(__DIR__) . '/vendor/dotenv/Validator.php' );
	require_once( dirname(__DIR__) . '/vendor/bcrypt/wp-password-bcrypt.php' );
	
	// Setup configuration and load WordPress
	require_once( dirname(__DIR__) . '/config/config.php' );
	require_once( dirname(__DIR__) . '/config/licenses.php' );
	require_once( ABSPATH . 'wp-settings.php' );